name: Build e Análise Java

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read
  security-events: write  # necessário pro CodeQL subir resultado SARIF

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache do Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('app/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build com Maven
        working-directory: app
        run: ./mvnw clean install

  codeql:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Inicializar CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Build do código para análise
        working-directory: app
        run: ./mvnw compile -DskipTests

      - name: Executar análise CodeQL
        uses: github/codeql-action/analyze@v3
